/**
 * Override (增强/覆写) domain model.
 *
 * An override is a post-processing step attached to a subscription's base mihomo
 * document. It is re-applied each time the runtime kernel config is generated,
 * so a profile can be customized (rules, groups, DNS, mode, custom fields)
 * without editing the subscription file itself — and without losing the
 * customization on the next subscription refresh.
 *
 * Two kinds are supported:
 *  - `yaml`: a YAML document deep-merged into the base config. Array keys may
 *    use `+key` (prepend) / `key+` (append) modifiers to combine rule lists
 *    instead of replacing them.
 *  - `js`: a JavaScript snippet defining `main(config)`, run in a sealed VM
 *    sandbox. It may mutate `config` in place and/or return a new config object;
 *    any exception fails open (the prior config is kept) and is reported.
 */

/** How an override body is interpreted. */
export type OverrideKind = 'yaml' | 'js'

/** Where an override applies. */
export type OverrideScope = 'global' | 'profile'

/** A single persisted override definition (the user-authored metadata + body). */
export interface OverrideItem {
  /** Stable id, generated by the main process. */
  id: string
  /** User-facing name. */
  name: string
  kind: OverrideKind
  /** When false the override is skipped in the pipeline. */
  enabled: boolean
  scope: OverrideScope
  /** Required (non-null) when scope === 'profile'; ignored otherwise. */
  profileId: string | null
  /** Ascending application order (lower runs first). */
  order: number
  /** The override document (YAML body or JS source). */
  content: string
  /** Last modification time, epoch milliseconds. */
  updatedAt: number
}

/** Author-editable fields used when creating or updating an override. */
export interface OverrideInput {
  name: string
  kind: OverrideKind
  scope: OverrideScope
  profileId: string | null
  content: string
}

/** The snapshot of every override the renderer observes. */
export interface OverridesSnapshot {
  items: OverrideItem[]
}

export const EMPTY_OVERRIDES: OverridesSnapshot = { items: [] }

const KINDS = new Set<OverrideKind>(['yaml', 'js'])
const SCOPES = new Set<OverrideScope>(['global', 'profile'])

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/**
 * Coerce an arbitrary value into a valid {@link OverrideItem}. Unknown or
 * malformed fields fall back to safe defaults so the renderer never crashes on a
 * stale or hand-edited snapshot. The strict validation that gates writes lives
 * in the main-process IPC boundary instead.
 */
export function coerceOverrideItem(input: unknown): OverrideItem {
  const source = isRecord(input) ? input : {}
  const kind: OverrideKind = KINDS.has(source.kind as OverrideKind) ? (source.kind as OverrideKind) : 'yaml'
  const scope: OverrideScope = SCOPES.has(source.scope as OverrideScope) ? (source.scope as OverrideScope) : 'global'
  let profileId: string | null = null
  if (scope === 'profile' && typeof source.profileId === 'string' && source.profileId.trim().length > 0) {
    profileId = source.profileId
  }
  return {
    id: typeof source.id === 'string' ? source.id : '',
    name: typeof source.name === 'string' ? source.name : '未命名覆写',
    kind,
    enabled: typeof source.enabled === 'boolean' ? source.enabled : true,
    scope,
    profileId,
    order: typeof source.order === 'number' && Number.isFinite(source.order) ? source.order : 0,
    content: typeof source.content === 'string' ? source.content : '',
    updatedAt: typeof source.updatedAt === 'number' ? source.updatedAt : 0
  }
}

/** Coerce a snapshot of override items; malformed entries are dropped. */
export function coerceOverridesSnapshot(input: unknown): OverridesSnapshot {
  if (!isRecord(input) || !Array.isArray(input.items)) return { ...EMPTY_OVERRIDES }
  return { items: input.items.map(coerceOverrideItem) }
}
